
services:
  external:
    container_name: external
    # The name of the image that will be created when building this container
    image: external-website:latest
    build:
      context: .
      dockerfile: Dockerfile
    user: "node"
    environment:
      # Internal server error messages will not send stacktrace to the browser in production
      - NODE_ENV=production
      # Sets the timezone of the containers OS
      - TZ=Pacific/Auckland
    # Points to a file with the sensitive environment variables
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 3000:5050
    labels:
      # Stops watchtower from updating this container
      - "com.centurylinklabs.watchtower.enable=false"

# Tells docker to use an IP from this range when creating this containers network. Important to avoid IP conflicts on your network.
# Can be done globally with a setting in docker. 
networks:
  external:
      driver: default
      ipam:
          config:
              - subnet: "172.20.0.0/16"