// Constants

const RoomTypes = {
    SUPER_DELUXE_DOUBLE_BED: "SUPER DELUXE DOUBLE BED",
    DELUXE_DOUBLE_BED: "DELUXE DOUBLE BED",
    SUPER_DELUXE_TRIPLE_BED: "SUPER DELUXE TRIPLE BED",
    DELUXE_TRIPLE_BED: "DELUXE TRIPLE BED"
};

export default RoomTypes;
// export default ROOM_TYPES;


